import type { AvatarData } from '../types';

export const mockAvatars: AvatarData[] = [
  {
    id: 'mock-01',
    emotionAnswers: [
      { imageId: 1, emotion: 'malinconia', rank: 1 },
      { imageId: 2, emotion: 'quiete', rank: 2 },
    ],
    gesture: 'raccogliere',
    tempoDescription: 'il vecchio orologio della nonna',
    tempoValue: 0.2,
    color: '#6e7fc9',
    shapeType: 'round',
    pulseSpeed: 1.7,
    poeticReading: 'Un artista che raccoglie il mondo con malinconia. Il suo tempo scorre attraverso il vecchio orologio della nonna.',
    position: [-6, 1, -4],
  },
  {
    id: 'mock-02',
    emotionAnswers: [
      { imageId: 3, emotion: 'tensione', rank: 1 },
      { imageId: 4, emotion: 'inquietudine', rank: 2 },
    ],
    gesture: 'interrompere',
    tempoDescription: 'un cantiere abbandonato che continua a crescere',
    tempoValue: 0.85,
    color: '#c96e6e',
    shapeType: 'angular',
    pulseSpeed: 0.73,
    poeticReading: 'Un artista che interrompe il mondo con tensione. Il suo tempo scorre attraverso un cantiere abbandonato che continua a crescere.',
    position: [5, -2, 3],
  },
  {
    id: 'mock-03',
    emotionAnswers: [
      { imageId: 5, emotion: 'meraviglia', rank: 1 },
      { imageId: 6, emotion: 'gioia', rank: 2 },
    ],
    gesture: 'osservare',
    tempoDescription: 'la luce che cambia sulle case al tramonto',
    tempoValue: 0.5,
    color: '#c9a96e',
    shapeType: 'hybrid',
    pulseSpeed: 1.25,
    poeticReading: 'Un artista che osserva il mondo con meraviglia. Il suo tempo scorre attraverso la luce che cambia sulle case al tramonto.',
    position: [2, 2, -6],
  },
  {
    id: 'mock-04',
    emotionAnswers: [
      { imageId: 1, emotion: 'quiete', rank: 1 },
      { imageId: 3, emotion: 'malinconia', rank: 2 },
    ],
    gesture: 'ripetere',
    tempoDescription: 'la pioggia sul vetro ogni mattina',
    tempoValue: 0.15,
    color: '#6ec9a9',
    shapeType: 'round',
    pulseSpeed: 1.78,
    poeticReading: 'Un artista che ripete il mondo con quiete. Il suo tempo scorre attraverso la pioggia sul vetro ogni mattina.',
    position: [-3, -1, 5],
  },
  {
    id: 'mock-05',
    emotionAnswers: [
      { imageId: 2, emotion: 'inquietudine', rank: 1 },
      { imageId: 5, emotion: 'tensione', rank: 2 },
    ],
    gesture: 'costruire',
    tempoDescription: 'il suono dei passi nel corridoio vuoto',
    tempoValue: 0.7,
    color: '#a96ec9',
    shapeType: 'angular',
    pulseSpeed: 0.95,
    poeticReading: 'Un artista che costruisce il mondo con inquietudine. Il suo tempo scorre attraverso il suono dei passi nel corridoio vuoto.',
    position: [7, 0, -2],
  },
  {
    id: 'mock-06',
    emotionAnswers: [
      { imageId: 4, emotion: 'gioia', rank: 1 },
      { imageId: 6, emotion: 'meraviglia', rank: 2 },
    ],
    gesture: 'raccogliere',
    tempoDescription: 'i mercati del sabato mattina',
    tempoValue: 0.6,
    color: '#c9c96e',
    shapeType: 'round',
    pulseSpeed: 1.1,
    poeticReading: 'Un artista che raccoglie il mondo con gioia. Il suo tempo scorre attraverso i mercati del sabato mattina.',
    position: [-5, 2, 2],
  },
  {
    id: 'mock-07',
    emotionAnswers: [
      { imageId: 1, emotion: 'malinconia', rank: 1 },
      { imageId: 4, emotion: 'tensione', rank: 2 },
    ],
    gesture: 'osservare',
    tempoDescription: 'le fotografie ingiallite di luoghi mai visitati',
    tempoValue: 0.3,
    color: '#6e7fc9',
    shapeType: 'hybrid',
    pulseSpeed: 1.55,
    poeticReading: 'Un artista che osserva il mondo con malinconia. Il suo tempo scorre attraverso le fotografie ingiallite di luoghi mai visitati.',
    position: [0, -3, -7],
  },
  {
    id: 'mock-08',
    emotionAnswers: [
      { imageId: 3, emotion: 'meraviglia', rank: 1 },
      { imageId: 2, emotion: 'quiete', rank: 2 },
    ],
    gesture: 'costruire',
    tempoDescription: 'la prima pagina di ogni libro trovato per caso',
    tempoValue: 0.45,
    color: '#c9a96e',
    shapeType: 'angular',
    pulseSpeed: 1.33,
    poeticReading: 'Un artista che costruisce il mondo con meraviglia. Il suo tempo scorre attraverso la prima pagina di ogni libro trovato per caso.',
    position: [-7, -2, -1],
  },
  {
    id: 'mock-09',
    emotionAnswers: [
      { imageId: 5, emotion: 'quiete', rank: 1 },
      { imageId: 1, emotion: 'gioia', rank: 2 },
    ],
    gesture: 'ripetere',
    tempoDescription: 'il gatto che ritorna ogni sera alla stessa ora',
    tempoValue: 0.1,
    color: '#6ec9a9',
    shapeType: 'round',
    pulseSpeed: 1.85,
    poeticReading: 'Un artista che ripete il mondo con quiete. Il suo tempo scorre attraverso il gatto che ritorna ogni sera alla stessa ora.',
    position: [4, 3, 4],
  },
  {
    id: 'mock-10',
    emotionAnswers: [
      { imageId: 6, emotion: 'tensione', rank: 1 },
      { imageId: 3, emotion: 'inquietudine', rank: 2 },
    ],
    gesture: 'interrompere',
    tempoDescription: 'le conversazioni spezzate in mezzo alla strada',
    tempoValue: 0.9,
    color: '#c96e6e',
    shapeType: 'angular',
    pulseSpeed: 0.65,
    poeticReading: 'Un artista che interrompe il mondo con tensione. Il suo tempo scorre attraverso le conversazioni spezzate in mezzo alla strada.',
    position: [-2, 1, 7],
  },
  {
    id: 'mock-11',
    emotionAnswers: [
      { imageId: 2, emotion: 'inquietudine', rank: 1 },
      { imageId: 6, emotion: 'malinconia', rank: 2 },
    ],
    gesture: 'raccogliere',
    tempoDescription: 'gli oggetti dimenticati sui davanzali',
    tempoValue: 0.4,
    color: '#a96ec9',
    shapeType: 'round',
    pulseSpeed: 1.4,
    poeticReading: 'Un artista che raccoglie il mondo con inquietudine. Il suo tempo scorre attraverso gli oggetti dimenticati sui davanzali.',
    position: [6, -1, -5],
  },
  {
    id: 'mock-12',
    emotionAnswers: [
      { imageId: 4, emotion: 'gioia', rank: 1 },
      { imageId: 5, emotion: 'meraviglia', rank: 2 },
    ],
    gesture: 'osservare',
    tempoDescription: 'il momento in cui i bambini smettono di correre',
    tempoValue: 0.55,
    color: '#c9c96e',
    shapeType: 'hybrid',
    pulseSpeed: 1.18,
    poeticReading: 'Un artista che osserva il mondo con gioia. Il suo tempo scorre attraverso il momento in cui i bambini smettono di correre.',
    position: [-4, -3, -3],
  },
];
